
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Tokens {
  /* terminals */
  public static final int MAIS = 3;
  public static final int MENOS = 4;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int VEZES = 5;
  public static final int NUMERO = 12;
  public static final int ID = 10;
  public static final int DIVIDIR = 6;
  public static final int error = 1;
  public static final int RPAREN = 9;
  public static final int LPAREN = 8;
  public static final int MENOSUNIT = 7;
  public static final int ATRIB = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "MAIS",
  "MENOS",
  "VEZES",
  "DIVIDIR",
  "MENOSUNIT",
  "LPAREN",
  "RPAREN",
  "ID",
  "ATRIB",
  "NUMERO"
  };
}

